services:
  postgres_eventostec1:
    container_name: postgres_api_eventostec1
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
#  jaeger_ifood:
#    container_name: jaeger_ifood
#    image: jaegertracing/all-in-one:1.6
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14268:14268"
#      - "9411:9411"
#  prometheus_ifood:
#    container_name: prometheus_ifood
#    image: prometheus-ifood
#    network_mode: "host"